# Generated by Django 3.2.25 on 2024-04-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0009_alter_subro_organization_root_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subro_admin', '0002_auto_20240403_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], default='UPDATE', max_length=10)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subro Coins',
                'verbose_name_plural': 'Subro Coins',
            },
        ),
    ]
