# Generated by Django 3.2.25 on 2024-05-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subro_admin', '0003_orglogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orglogs',
            options={},
        ),
    ]
