# Generated by Django 3.2.25 on 2024-05-16 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dashboard', '0020_alter_subro_org_wallet_transaction_origin_wallet'),
        ('subro_admin', '0004_alter_orglogs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('SIGN', 'SIGN'), ('ARCHIVE', 'ARCHIVE'), ('DELETE', 'DELETE')], default='CREATE', max_length=20)),
                ('entity_type', models.CharField(choices=[('ORGANIZATION', 'ORGANIZATION'), ('OFFER', 'OFFER'), ('RESPONSE', 'RESPONSE')], default='ORGANIZATION', max_length=20)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrgLogs',
        ),
    ]
