# Generated by Django 3.2.25 on 2024-05-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0020_alter_subro_org_wallet_transaction_origin_wallet'),
        ('subro_admin', '0005_auto_20240516_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubroKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('encrypted_aes_key', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_keys', to='user_dashboard.subro_organization')),
            ],
        ),
    ]
