# Generated by Django 3.2.25 on 2024-05-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0020_alter_subro_org_wallet_transaction_origin_wallet'),
        ('subro_admin', '0006_subrokey'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrokey',
            name='assigned_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_key', to='user_dashboard.subro_organization_user'),
        ),
    ]
