# Generated by Django 3.2.25 on 2024-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subro_admin', '0007_subrokey_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrokey',
            name='key_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
