# Generated by Django 5.0.2 on 2024-02-22 01:37

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from django.db import migrations
from django.contrib.auth.models import Group

def create_initial_groups(apps, schema_editor):
    Group.objects.get_or_create(name='admin')
    Group.objects.get_or_create(name='arbitrator')
    Group.objects.get_or_create(name='org_root')
    Group.objects.get_or_create(name='org_user')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subro_offer_org_vehicle_vin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='subro_org_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_transaction', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subro_organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subro_organization_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subro_resp_org_vehicle_vin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='sent_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('arbitration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.arbitration')),
            ],
        ),
        migrations.CreateModel(
            name='subro_offer_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responderCompany', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('accidentDate', models.DateField()),
                ('offerAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservedOfferAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('arbitrationBinding', models.BooleanField(default=False)),
                ('aiArbitration', models.BooleanField(default=False)),
                ('case_files', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to='')),
                ('offerVehicleVin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_offer_org_vehicle_vin')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization_user')),
                ('respondVehicleVin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_resp_org_vehicle_vin')),
            ],
        ),
        migrations.AddField(
            model_name='arbitration',
            name='subro_offer_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_offer_request'),
        ),
        migrations.CreateModel(
            name='subro_org_wallet_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_org_wallet')),
            ],
        ),
        migrations.AddField(
            model_name='subro_org_wallet',
            name='subro_organization_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization'),
        ),
        migrations.CreateModel(
            name='subro_organization_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('subro_organization_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization_user')),
            ],
        ),
        migrations.CreateModel(
            name='subro_offer_responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_accepted', models.BooleanField(default=False)),
                ('subro_offer_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_offer_request')),
                ('offer_sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization_user')),
            ],
        ),
        migrations.CreateModel(
            name='subro_vehicle_vin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleVin', models.CharField(max_length=17)),
                ('subro_organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization')),
            ],
        ),
        migrations.AddField(
            model_name='subro_resp_org_vehicle_vin',
            name='vin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_vehicle_vin'),
        ),
        migrations.AddField(
            model_name='subro_offer_org_vehicle_vin',
            name='vin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_vehicle_vin'),
        ),
        migrations.CreateModel(
            name='subroUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('acceptsAiArbitrationBinding', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subro User',
                'verbose_name_plural': 'Subro Users',
            },
        ),
        migrations.AddField(
            model_name='subro_organization_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subrouser'),
        ),
        migrations.AddField(
            model_name='arbitration',
            name='arbitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subrouser'),
        ),
        migrations.RunPython(create_initial_groups),
    ]
