# Generated by Django 5.0.2 on 2024-02-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subro_vehicle_vin',
            name='VehicleVin',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
