# Generated by Django 5.0.2 on 2024-02-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_alter_subro_vehicle_vin_vehiclevin'),
    ]

    operations = [
        migrations.AddField(
            model_name='subro_offer_org_vehicle_vin',
            name='organization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subro_resp_org_vehicle_vin',
            name='organization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization'),
            preserve_default=False,
        ),
    ]
