# Generated by Django 5.0.2 on 2024-02-27 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_subro_offer_org_vehicle_vin_organization_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subro_organization_user',
            name='company',
        ),
        migrations.AddField(
            model_name='subro_organization_user',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization'),
            preserve_default=False,
        ),
    ]
