# Generated by Django 5.0.2 on 2024-02-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_remove_subro_organization_user_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subro_organization_user',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='subro_organization_user',
            old_name='user_id',
            new_name='user',
        ),
    ]
