# Generated by Django 5.0.2 on 2024-03-05 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_rename_company_id_subro_organization_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subro_offer_request',
            name='responderCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization'),
        ),
    ]
