# Generated by Django 3.2.25 on 2024-04-17 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dashboard', '0008_auto_20240403_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subro_offer_request',
            name='case_files',
        ),
        migrations.AlterField(
            model_name='subro_organization',
            name='root_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='subro_offer_request_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_offer_request')),
            ],
        ),
    ]
