# Generated by Django 3.2.25 on 2024-04-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0009_alter_subro_organization_root_user'),
        ('user_dashboard', '0009_auto_20240417_1104'),
    ]

    operations = [
    ]
