# Generated by Django 3.2.25 on 2024-04-25 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0010_merge_20240419_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='subro_offer_request_file',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subro_offer_request_file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=True),
        ),
    ]
