# Generated by Django 3.2.25 on 2024-04-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0012_auto_20240425_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='subro_offer_request',
            name='status',
            field=models.CharField(choices=[('0/2 keys', '0/2 keys'), ('1/2 keys', '1/2 keys'), ('Signed', 'Signed'), ('Arbitration', 'Arbitration'), ('AI', 'AI'), ('Resolved', 'Resolved')], default='0/2 keys', max_length=20),
        ),
    ]
