# Generated by Django 3.2.25 on 2024-05-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0014_auto_20240505_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='subro_org_wallet_transaction',
            name='destination_wallet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_wallet', to='user_dashboard.subro_org_wallet'),
        ),
        migrations.AddField(
            model_name='subro_org_wallet_transaction',
            name='status',
            field=models.CharField(choices=[('SIGNED', 'SIGNED'), ('NOT_SIGNED', 'NOT_SIGNED')], default='SIGNED', max_length=10),
        ),
        migrations.AddField(
            model_name='subro_org_wallet_transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('MINT', 'MINT'), ('MOVE', 'MOVE')], default='BUY', max_length=10),
        ),
    ]
