# Generated by Django 3.2.25 on 2024-05-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0017_subro_offer_request_cycle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subro_org_wallet_transaction',
            name='status',
            field=models.CharField(choices=[('SIGNED', 'SIGNED'), ('NOT_SIGNED', 'NOT_SIGNED'), ('AP1', 'AP1'), ('AP2', 'AP2'), ('AP3', 'AP3'), ('FAILED', 'FAILED')], default='SIGNED', max_length=10),
        ),
        migrations.AlterField(
            model_name='subro_organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPEND', 'SUSPEND')], default='ACTIVE', max_length=10),
        ),
    ]
