# Generated by Django 3.2.25 on 2024-05-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0018_auto_20240509_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subro_vehicle_vin',
            name='VehicleVin',
            field=models.CharField(max_length=17),
        ),
    ]
