# Generated by Django 3.2.25 on 2024-05-16 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0019_alter_subro_vehicle_vin_vehiclevin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subro_org_wallet_transaction',
            name='origin_wallet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_wallet', to='user_dashboard.subro_org_wallet'),
        ),
    ]
