# Generated by Django 3.2.25 on 2024-05-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0021_subro_offer_request_file_uploaded_by_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subro_offer_request_file',
            old_name='file_type',
            new_name='file_format',
        ),
    ]
