# Generated by Django 3.2.25 on 2024-06-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0023_auto_20240603_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='subro_offer_responder',
            name='status',
            field=models.CharField(choices=[('0/2 keys', 'Zero Two Keys'), ('1/2 keys', 'One Two Keys'), ('Signed', 'Signed')], default='0/2 keys', max_length=20),
        ),
        migrations.CreateModel(
            name='SubroResponderSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_organization_user')),
            ],
        ),
        migrations.AddField(
            model_name='subro_offer_responder',
            name='signatures',
            field=models.ManyToManyField(blank=True, related_name='signatures', to='user_dashboard.SubroResponderSignature'),
        ),
    ]
