# Generated by Django 3.2.25 on 2024-06-10 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0025_auto_20240604_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrooffersignature',
            name='offer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='user_dashboard.subro_offer_request'),
        ),
        migrations.AlterField(
            model_name='subrorespondersignature',
            name='offer_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder_signatures', to='user_dashboard.subro_offer_responder'),
        ),
    ]
