# Generated by Django 3.2.25 on 2024-06-11 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dashboard', '0027_subro_offer_request_arbitratedamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitratorUserActionsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('APPROVE_CLAIM', 'APPROVE_CLAIM'), ('REJECT_CLAIM', 'REJECT_CLAIM')], default='APPROVE_CLAIM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.subro_offer_request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
